---
#
# Ansible managed
#
repository:
  description: Install and configure redis on your system.
  homepage: https://buluma.github.io/
  topics: redis, server, system, ansible, molecule, tox, playbook, hacktoberfest
